### ISSUE TITLE
2014 Session 306 Null Timecodes

### ISSUE THREAD

**Issue by bryanluby** [ASCIIwwdc/asciiwwdc.com#22]
This web service call for 2014 session 306 is returning some null timecodes:

`curl -i -X GET -H "Accept: application/json" "http://asciiwwdc.com/2014/sessions/306"`

```json
"timecodes": [
        13.046,
        13.716,
        15.116,
        16.896,
        18.586,
        19.676,
        null,
        23.236,
        null,
        27.246,
        null,
        30.266,
        33.516,
        37.116,
        null,
        38.956,
        null,
        etc...
```

**Comment by natecook1000** [comment]
Thanks for the report, @bryanluby — this should be fixed by ASCIIwwdc/wwdc-session-transcripts@487b2814a445333ac291921dbbcce12a7fd2914b. Let me know if it's still a problem or you see others!
