### ISSUE TITLE
Layout is not usable in small browser windows

### ISSUE THREAD

**Issue by adurdin** [ASCIIwwdc/asciiwwdc.com#26]
The container element on the site has a fixed width of 950px, and no minimum horizontal margins.

When the site is viewed in a small browser window—for example, when viewing the asciiwwdc transcript side by side with the PDF slides—this fixed width then requires horizontal scrolling, which makes it really hard to read. And the lack of a minimum horizontal margin means the text abuts the edges of the window, also impairing readability.

Here is the site as it appears in a small browser window, demonstrating the usability issues:
![problematic](https://cloud.githubusercontent.com/assets/81129/10715440/1981de06-7b0f-11e5-94f5-897007f54785.png)

Here is the site after tweaking the `[role=container]` css rules to remove the `width: 950px` rule, and to alter the `margin 0 auto` rule to `margin 0 20px` (to show the need for a minimum margin).
![tweaked](https://cloud.githubusercontent.com/assets/81129/10715441/1f52b990-7b0f-11e5-861e-bf4db44ec534.png)

**Comment by natecook1000** [comment]
Hi @adurdin — sorry for not responding sooner! I know I've tweaked the mobile CSS some; can you check and see if things look better for you?

**Comment by adurdin** [comment]
Yep, this works beautifully now! Thanks!
