### ISSUE TITLE
Copying transcript from Apple Website

### ISSUE THREAD

**Issue by ignazioc** [ASCIIwwdc/asciiwwdc.com#33]
Hi, Apple now provides full transcript of the WWDC videos.

Is there maybe a legal reason why we can't just copy the content from there and make is searchable?

thanks

**Comment by mattt** [comment]
Hi @ignazioc, this is indeed how most of the transcripts for WWDC sessions are sourced. Or am I misunderstanding your question?

**Comment by ignazioc** [comment]
I thought there was an audio-transcription software :P
