### ISSUE TITLE
Any chance to update WWDC 2019 transcripts?

### ISSUE THREAD

**Issue by wongzigii** [ASCIIwwdc/asciiwwdc.com#35]

**Comment by cgravolet** [comment]
https://developer.apple.com/news/?id=07102019a

**Comment by mattt** [comment]
ASCIIwwdc is now updated with transcripts from WWDC 2019.

Additional transcripts are available in Chinese (Simplified), Japanese, Korean, and Spanish [here](https://github.com/ASCIIwwdc/wwdc-session-transcripts).
